### ISSUE TITLE
How to add context sensitive commands?

### ISSUE THREAD

**Issue by sanketsahu** [DerekRies/angular-palette#2]
Amazing work there! This is AWESOME! I was just going to create one like this but I found yours. This is exactly what I had in my mind.

I want to know how can I add context sensitive commands? Say, if I am on a route which has this "Delete" button on the page. And I want a keyboard shortcut which can invoke that Delete button when I am on that page.

**Comment by sanketsahusoft** [comment]
Also, I can help you to improve this one by adding more features.

**Comment by DerekRies** [comment]
I don't work on (or even use) this project anymore, it's pretty much abandoned, so sorry for that. I'd recommend just forking the project for now. 

You should be able to do what you want in your "Delete" example by using the paletteService.exportCommands method in your controller for that particular route. At least I think that's what you were asking for.

**Comment by sanketsahusoft** [comment]
Thanks a lot for the reply. I am using this as a starting point. I will let you know if I publish a new and improved one.
